---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Backup and Snapshots"
      solveButton: false
    - name: module-02
      label: "Infrastructure Reporting"
      solveButton: false
    - name: module-03
      label: "Windows Reporting"
      solveButton: false

tabs:
  - name: aap
    url: https://control-${guid}.${domain}/
    external: false
  - name: ">_ control"
    url: /wetty
  - name: Webapp
    url: https://podman-host-${guid}.${domain}/index.html
    external: false
  - name: ServiceNow
    url: https://ansible.service-now.com
    external: true
  - name: Red Hat Insights
    url: https://console.redhat.com
    external: true
